require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ShoesController do

  # This should return the minimal set of attributes required to create a valid
  # Shoe. As you add validations to Shoe, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all shoes as @shoes" do
      shoe = Shoe.create! valid_attributes
      get :index
      assigns(:shoes).should eq([shoe])
    end
  end

  describe "GET show" do
    it "assigns the requested shoe as @shoe" do
      shoe = Shoe.create! valid_attributes
      get :show, :id => shoe.id
      assigns(:shoe).should eq(shoe)
    end
  end

  describe "GET new" do
    it "assigns a new shoe as @shoe" do
      get :new
      assigns(:shoe).should be_a_new(Shoe)
    end
  end

  describe "GET edit" do
    it "assigns the requested shoe as @shoe" do
      shoe = Shoe.create! valid_attributes
      get :edit, :id => shoe.id
      assigns(:shoe).should eq(shoe)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Shoe" do
        expect {
          post :create, :shoe => valid_attributes
        }.to change(Shoe, :count).by(1)
      end

      it "assigns a newly created shoe as @shoe" do
        post :create, :shoe => valid_attributes
        assigns(:shoe).should be_a(Shoe)
        assigns(:shoe).should be_persisted
      end

      it "redirects to the created shoe" do
        post :create, :shoe => valid_attributes
        response.should redirect_to(Shoe.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved shoe as @shoe" do
        # Trigger the behavior that occurs when invalid params are submitted
        Shoe.any_instance.stub(:save).and_return(false)
        post :create, :shoe => {}
        assigns(:shoe).should be_a_new(Shoe)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Shoe.any_instance.stub(:save).and_return(false)
        post :create, :shoe => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested shoe" do
        shoe = Shoe.create! valid_attributes
        # Assuming there are no other shoes in the database, this
        # specifies that the Shoe created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Shoe.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => shoe.id, :shoe => {'these' => 'params'}
      end

      it "assigns the requested shoe as @shoe" do
        shoe = Shoe.create! valid_attributes
        put :update, :id => shoe.id, :shoe => valid_attributes
        assigns(:shoe).should eq(shoe)
      end

      it "redirects to the shoe" do
        shoe = Shoe.create! valid_attributes
        put :update, :id => shoe.id, :shoe => valid_attributes
        response.should redirect_to(shoe)
      end
    end

    describe "with invalid params" do
      it "assigns the shoe as @shoe" do
        shoe = Shoe.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Shoe.any_instance.stub(:save).and_return(false)
        put :update, :id => shoe.id, :shoe => {}
        assigns(:shoe).should eq(shoe)
      end

      it "re-renders the 'edit' template" do
        shoe = Shoe.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Shoe.any_instance.stub(:save).and_return(false)
        put :update, :id => shoe.id, :shoe => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested shoe" do
      shoe = Shoe.create! valid_attributes
      expect {
        delete :destroy, :id => shoe.id
      }.to change(Shoe, :count).by(-1)
    end

    it "redirects to the shoes list" do
      shoe = Shoe.create! valid_attributes
      delete :destroy, :id => shoe.id
      response.should redirect_to(shoes_url)
    end
  end

end
